# Generated by Django 4.1.2 on 2022-10-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_alter_attraction_slug_alter_park_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='parks',
        ),
        migrations.RemoveField(
            model_name='park',
            name='location',
        ),
    ]
