# Generated by Django 4.1.2 on 2022-10-26 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractions', '0003_remove_attraction_parks_remove_park_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likess', to=settings.AUTH_USER_MODEL),
        ),
    ]
