# Generated by Django 4.1.2 on 2022-10-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('email', models.CharField(max_length=300, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_people',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
    ]
