# Generated by Django 4.1.2 on 2022-10-30 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractions', '0006_contact_book_number_of_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
                ('preferred_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
